version: '3'

services:
  neo4j:
    image: neo4j:4.0.3
    hostname: ${NEO4j_NAME}
    container_name: ${NEO4j_NAME}
    ports:
      - 7474:${NEO4j_HTTP}
      - 7473:${NEO4j_HTTPS}
      - 7687:${NEO4j_BOLT}
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_dbms_unmanaged__extension__classes: org.neo4j.graphql=/graphql
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_logs_query_threshold: 0s
      NEO4J_dbms.logs.query.enabled: "INFO"
      NEO4J_cypher_lenient__create__relationship: "true"
      NEO4J_apoc_trigger_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_shell_enabled: "true"
    # NEO4J_ENCRYPTED: "true"
    volumes:
      - ./Dependents/neo4j/plugins:/plugins
      - ./Dependents/${NEO4j_NAME}/data:/data
    # - ./Dependents/${NEO4j_NAME}/conf:/config

  api:
    build: ./api
    hostname: ${GQL_NAME}
    ports:
      - 4002:${GQL_PORT}
    container_name: ${GQL_NAME}
    environment:
      - NEO4J_URI=bolt://${NEO4j_NAME}:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - GRAPHQL_SERVER_PORT=4002
      - GRAPHQL_SERVER_PATH=/graphql
      - GRAPHQL_SERVER_HOST=${GQL_NAME}
      - JWT_SECRET=${GQL_JWT_SECRET}
      - AUTH_DIRECTIVES_ROLE_KEY=${GQL_AUTH_DIRECTIVES_ROLE_KEY}
    # - NEO4J_ENCRYPTED=true
    volumes:
      - ./schema:/schema
    links:
    - neo4j
    depends_on:
    - neo4j

volumes:
  schema:
