version: '3'

services:
  neo4j:
    image: neo4j:3.5
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/wibble
      NEO4J_dbms_unmanaged__extension__classes: org.neo4j.graphql=/graphql
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      #NEO4J_kafka_zookeeper_connect: zookeeper:2181
      #NEO4J_kafka_bootstrap_servers: broker:9093
      NEO4J_dbms_logs_query_threshold: 0s
      NEO4J_dbms_logs_query_enabled: "true"
      NEO4J_cypher_lenient__create__relationship: "true"
      NEO4J_apoc_trigger_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ./Dependents/neo4j/plugins:/plugins
      - ./Dependents/neo4j/data:/data
      - ./Dependents/neo4j/conf:/config

  api:
    build: ./api
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=wibble
      - GRAPHQL_LISTEN_PORT=4002
      - GRAPHQL_URI=http://api:4002/graphql
    ports:
      - 4002:4002
    links:
    - neo4j
    depends_on:
    - neo4j
